--creating default users 
INSERT INTO userDetails (userName, name, password) VALUES ('Harry12', 'Harry Keane', 'password'),
('Dylannnn', 'Dylan Drake','password556'),
('Marky', 'Mark McGrath','password'),
('Jonny', 'Jonathon Brinn','password556'),
('Murph', 'Ian Murphy','password115'),
('Dan', 'Daniel Lane','password55'),
('Soph', 'Sophie Moran','password112'),
('Albahe', 'Ailbhe Lynott','password556'),
('Bert', 'Robert Ryan','password'),
('Emmmmmma', 'Emma O''Connor','password556'),
('Martinahhh', 'Martina Connor','password6'),
('MikeRoss', 'James Patrick Adams','password65'),
('DarthVader', 'Anakin Skywalker','password223'),
('PickleRick', 'Rick Sanchez','password778'),
('Windows', 'Bill Gates','password8'),
('BillyTheKid', 'Billy Drake','password55'),
('Cooney', 'Darragh Collins','password56'),
('Ger', 'Gerry Keane','password'),
('Mags', 'Maggie Grady','password556'),
('Tommy', 'Thomas Selby','password556');
